apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  templete:
    metadata:
    label:
        app: mysql	
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MY_SQL_ROOT_PASSWORD
          value: "Test@123"
        - name: MYSQL_DATABASE
          value: "bankappdb"
          ports:
          - containerPort: 3306
            name: mysql			  
appVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    ports:
    - port: 3306
    selector:
      app: mysql	
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp-deployment
spec:
  selector:
    matchLabels:
      app: bloggingapp
  replicas: 1
  template:
    metadata:
      labels:
        app: bloggingapp
    spec:
      containers:
      - name: bloggingapp
        image: alokkodzz/blogiingapp:latest # Updated image to private DockerHub image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-server:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyrectrieval=true
      - name: SPRING_DATASOURCE_USERNAME
        value: root
      - name: SPRING_DATASOURCE_PASSWORD
        value: Test@123
apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-service
spec:
  selector:
    app: bloggingapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080 
  type: LoadBalancer
